image: docker:25.0

stages:
  - build
  - test
  - deploy

build-image:
  stage: build
  image: registry.green-rabbit.net:5000/kimata/ubuntu-docker-build:latest

  script:
    # - docker rm $(docker ps -a --filter 'status=exited' -q) || true
    - export GIT_SSL_NO_VERIFY=1
    - git clone https://gitlab.green-rabbit.net/kimata/panel_config.git
    - mv panel_config/kindle_sensor.yaml config.yaml
    - git clone https://gitlab.green-rabbit.net/kimata/font.git private_font
    - mv private_font/* font
    - docker pull ${CI_REGISTRY_IMAGE} || true
    - docker build . -t ${CI_REGISTRY_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}

# サンプル設定ファイルで，問題なく動くかチェック
test-sample:
  stage: test

  script:
    - docker pull ${CI_REGISTRY_IMAGE}
    - docker run -t --label job=${CI_JOB_NAME} ${CI_REGISTRY_IMAGE} src/create_image.py -c config.example.yaml -o ${CI_JOB_NAME}.png
    - CID=`docker ps -q -l -f "ancestor=${CI_REGISTRY_IMAGE}" -f "label=job=${CI_JOB_NAME}"`
    - docker wait ${CID}
    - docker cp ${CID}:/opt/kindle_sensor/${CI_JOB_NAME}.png .

  artifacts:
    paths:
      - ${CI_JOB_NAME}.png

# 本番設定ファイルで，問題なく動くかチェック
test-regular:
  stage: test

  script:
    - docker pull ${CI_REGISTRY_IMAGE}
    - docker run -t --label job=${CI_JOB_NAME} ${CI_REGISTRY_IMAGE} src/create_image.py -o ${CI_JOB_NAME}.png
    - CID=`docker ps -q -l -f "ancestor=${CI_REGISTRY_IMAGE}" -f "label=job=${CI_JOB_NAME}"`
    - docker wait ${CID}
    - docker cp ${CID}:/opt/kindle_sensor/${CI_JOB_NAME}.png .

  artifacts:
    paths:
      - ${CI_JOB_NAME}.png

# 本番設定ファイルで，問題なく動くかチェック
test-display:
  stage: test

  variables:
    KINDLE_HOSTNAME: kindle-library

  script:
    - docker pull ${CI_REGISTRY_IMAGE}
    - docker run -t ${CI_REGISTRY_IMAGE} src/display_image.py -c config.yaml -t ${KINDLE_HOSTNAME} -s

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context kimata/kindle_sensor_panel:pod-rollout
    - kubectl --insecure-skip-tls-verify=true rollout restart -n panel deployment kindle-sensor-panel-deployment
